export var regions = [
    { "pattern": new RegExp(/Алтайский/i), "zone": 7 },
    { "pattern": new RegExp(/Амурская/i), "zone": 9 },
    { "pattern": new RegExp(/Архангельская/i), "zone": 3 },
    { "pattern": new RegExp(/Астраханская/i), "zone": 4 },
    { "pattern": new RegExp(/Башкортостан/i), "zone": 5 },
    { "pattern": new RegExp(/Белгородская/i), "zone": 3 },
    { "pattern": new RegExp(/Брянская/i), "zone": 3 },
    { "pattern": new RegExp(/Бурятия/i), "zone": 8 },
    { "pattern": new RegExp(/Владимирская/i), "zone": 3 },
    { "pattern": new RegExp(/Волгоградская/i), "zone": 4 },
    { "pattern": new RegExp(/Вологодская/i), "zone": 3 },
    { "pattern": new RegExp(/Воронобласть/i), "zone": 3 },
    { "pattern": new RegExp(/Дагестан/i), "zone": 3 },
    { "pattern": new RegExp(/Забайкальский край/i), "zone": 9 },
    { "pattern": new RegExp(/Ивановская/i), "zone": 3 },
    { "pattern": new RegExp(/Иркутская/i), "zone": 8 },
    { "pattern": new RegExp(/Кабардино-Балкарская/i), "zone": 3 },
    { "pattern": new RegExp(/Калининградская/i), "zone": 2 },
    { "pattern": new RegExp(/Калужская/i), "zone": 3 },
    { "pattern": new RegExp(/Карелия/i), "zone": 3 },
    { "pattern": new RegExp(/Кемерово/i), "zone": 7 },
    { "pattern": new RegExp(/Кемеровская/i), "zone": 7 },
    { "pattern": new RegExp(/Кировская/i), "zone": 3 },
    { "pattern": new RegExp(/Коми/i), "zone": 3 },
    { "pattern": new RegExp(/Костромская/i), "zone": 3 },
    { "pattern": new RegExp(/Краснодарский край/i), "zone": 3 },
    { "pattern": new RegExp(/Красноярский край/i), "zone": 7 },
    { "pattern": new RegExp(/Крым/i), "zone": 3 },
    { "pattern": new RegExp(/Курганская/i), "zone": 5 },
    { "pattern": new RegExp(/Курская/i), "zone": 3 },
    { "pattern": new RegExp(/Ленинградская/i), "zone": 3 },
    { "pattern": new RegExp(/Липецкая/i), "zone": 3 },
    { "pattern": new RegExp(/Марий Эл/i), "zone": 3 },
    { "pattern": new RegExp(/Мордовия/i), "zone": 3 },
    { "pattern": new RegExp(/Московская/i), "zone": 3 },
    { "pattern": new RegExp(/Мурманская/i), "zone": 3 },
    { "pattern": new RegExp(/Нижегородская/i), "zone": 3 },
    { "pattern": new RegExp(/Новгородская/i), "zone": 3 },
    { "pattern": new RegExp(/Новосибирская/i), "zone": 7 },
    { "pattern": new RegExp(/Омская/i), "zone": 6 },
    { "pattern": new RegExp(/Оренбургская/i), "zone": 5 },
    { "pattern": new RegExp(/Орловская/i), "zone": 3 },
    { "pattern": new RegExp(/Пензенская/i), "zone": 3 },
    { "pattern": new RegExp(/Пермский/i), "zone": 5 },
    { "pattern": new RegExp(/Приморск край/i), "zone": 1 },
    { "pattern": new RegExp(/Псковская/i), "zone": 3 },
    { "pattern": new RegExp(/Республика Саха/i), "zone": 9 },
    { "pattern": new RegExp(/Ростовская/i), "zone": 3 },
    { "pattern": new RegExp(/Рязанская/i), "zone": 3 },
    { "pattern": new RegExp(/Самарская/i), "zone": 4 },
    { "pattern": new RegExp(/Саратовская/i), "zone": 3 },
    { "pattern": new RegExp(/Свердловская/i), "zone": 5 },
    { "pattern": new RegExp(/Северная Осетия - Алания/i), "zone": 3 },
    { "pattern": new RegExp(/Смоленская/i), "zone": 3 },
    { "pattern": new RegExp(/Ставропольский край/i), "zone": 3 },
    { "pattern": new RegExp(/Тамбовская/i), "zone": 3 },
    { "pattern": new RegExp(/Татарстан/i), "zone": 3 },
    { "pattern": new RegExp(/Тверская/i), "zone": 3 },
    { "pattern": new RegExp(/Томская/i), "zone": 7 },
    { "pattern": new RegExp(/Тульская/i), "zone": 3 },
    { "pattern": new RegExp(/Тюменская/i), "zone": 5 },
    { "pattern": new RegExp(/Удмуртия/i), "zone": 4 },
    { "pattern": new RegExp(/Ульяновская/i), "zone": 4 },
    { "pattern": new RegExp(/Хабаровский край/i), "zone": 1 },
    { "pattern": new RegExp(/Ханты-Мансийский/i), "zone": 5 },
    { "pattern": new RegExp(/Челябинская/i), "zone": 5 },
    { "pattern": new RegExp(/Чечня/i), "zone": 3 },
    { "pattern": new RegExp(/Чувашия/i), "zone": 3 },
    { "pattern": new RegExp(/Ярославская/i), "zone": 3 }
]